config/routes.rb
Rails.application.routes.draw do

  root 'customer/restaurants#index'

  resources :sessions, only: [:new, :create, :destroy] # Yung

  namespace :customer do #Phil
    root '/customer/customers#show'
  end

  namespace :manager, shallow: true do
    root 'restaurants#show'
    resource(:restaurant, only:[:edit, :show, :update]) do
      resources(:reservations, only: []) do #Rich
        member do
          post 'approve'
          post 'reject'
        end
      end
    end

  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :restaurants, except: [:index]
    resources :managers, except: [:index]
  end

  scope module: 'customer' do
    resources :customers, except: [:index] do
      resources :reservations, only: [:index, :show, :edit, :update] do
        member do 
          patch 'cancel'
        end
      end
    end
    resources :restaurants, only: [:index, :show] do
      resources :reservations, only: [:new, :create]
    end
  end

end

=begin
Sessions - Phil
  Handles log/log out.
Customer - Yung
  List of available restaurants.
  Sign-up for Customers
Reservations - Phil
  Create a reservation.
  View a reservation.
  Cancel a reservation.
Restaurant - Rich
  View reservations.
  Approve reservation.
  Decline reservation.
Admin - Rich
  List of all restaurants
  Approve or decline membership requests.
  Create admins and restaurant users.

=end

app/models/customer.rb
class Customer < User
  has_many :reservations
  validates_format_of :phone_number, :with => /\d{3}[ -]?\d{3}[ -]?\d{4}/, :message => 'Phone number must be in the format XXX-XXX-XXXX. Dashes/spaces optional'
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    
    if @customer.save
      if current_user.kind_of?(Administrator)
        redirect_to admin_root_path
      elsif
        redirect_to customer_path(@customer.id)
      end
    else
      render :new
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])

    if @customer.update_attributes(customer_params)
      redirect_to customer_path
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :phone_number, :password, :password_confirmation)
  end
  
end

app/controllers/customer/reservations_controller.rb
class Customer::ReservationsController < ApplicationController
  before_action :current_user
  before_action :load_restaurant, except: [:cancel, :edit, :update]

  def index
    @reservations = current_user.reservations
  end

  def new
    @reservation = @restaurant.reservations.new
  end

  def create
    @reservation = @restaurant.reservations.build
    @reservation.party_size = params[:reservation][:party_size]
    @reservation.date = DateTime.new(*params[:reservation].values.map{|x| x.to_i }[0..4])
    @reservation.customer = current_user
    
    if @reservation.save
      puts @reservation.inspect
      redirect_to customer_path(@reservation.customer.id)
    else
      render :new
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @customer = current_user
  end
  
  def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update_attributes(reservation_params)
      redirect_to customer_path(current_user.id)
    else
      render :edit
    end
  end

  def cancel
    @reservation = current_user.reservations.find(params[:id])
    @reservation.status = :cancelled
    if @reservation.save
      redirect_to customer_path(current_user.id)
    else
      redirect_to customer_path(current_user.id)
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:party_size, :date, :customer_id, :restaurant_id)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/controllers/customer/restaurant_controller.rb
class Customer::RestaurantController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  # def restaurant_params
  #   params.require(:restaurant).permit(:name, :capacity, :phone_number, :street_number, :street_name, :city, :province, :country, :postal_code)
  # end
  
end

app/controllers/customer/restaurants_controller.rb
class Customer::RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  # def restaurant_params
  #   params.require(:restaurant).permit(:name, :capacity, :phone_number, :street_number, :street_name, :city, :province, :country, :postal_code)
  # end
  
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customer/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customer/customers/new.html.erb
<h1>Sign up</h1>

<%= form_for @customer do |f| %>

	<% if @customer.errors.any? %>
	<div>
		<h2>Form Invalid</h2>
		<ul>
			<% @customer.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
		
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div>
		<%= f.label :phone_number %>
		<%= f.text_field :phone_number %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div>
		<%= f.submit "Join" %>
	</div>
<% end %>

app/views/customer/customers/show.html.erb
<h1> <%= @customer.name %>'s Profile </h1>

<h2>Reservations</h2>
<%= link_to "View All Restaurants", restaurants_path %>
<% @customer.reservations.each do |reservation| %>
	<div>
		<p>Restaurant: <%= reservation.restaurant.name %></p>
		<p>Date: <%= reservation.date %></p>
		<p>Status: <%= reservation.status %></p>
		<p>Party Size: <%= reservation.party_size %></p>
	</div>
	<div>
		<%= link_to "View Restaurant", restaurant_path(reservation.restaurant)  %>
		<%= link_to "Cancel Reservation", cancel_customer_reservation_path(reservation.restaurant.id, reservation.id), method: :patch %>
	</div>
<% end %>