config/routes.rb
Rails.application.routes.draw do

  root 'customer/restaurants#index'

  resources :sessions, only: [:new, :create, :destroy] # Yung

  namespace :customer do #Phil
    root '/customer/customers#show'
  end

  namespace :manager, shallow: true do
    root 'restaurants#show'
    resource(:restaurant, only:[:edit, :show, :update]) do
      resources(:reservations, only: []) do #Rich
        member do
          post 'approve'
          post 'reject'
        end
      end
    end

  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :restaurants, except: [:index]
    resources :managers, except: [:index]
  end

  scope module: 'customer' do
    resources :customers, except: [:index] do
      resources :reservations, only: [:index, :show, :edit, :update] do
        member do 
          patch 'cancel'
        end
      end
    end
    resources :restaurants, only: [:index, :show] do
      resources :reservations, only: [:new, :create]
    end
  end

end

=begin
Sessions - Phil
  Handles log/log out.
Customer - Yung
  List of available restaurants.
  Sign-up for Customers
Reservations - Phil
  Create a reservation.
  View a reservation.
  Cancel a reservation.
Restaurant - Rich
  View reservations.
  Approve reservation.
  Decline reservation.
Admin - Rich
  List of all restaurants
  Approve or decline membership requests.
  Create admins and restaurant users.

=end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  # For the sake of simplicity this model does not attempt to handle time offsets.
  # We would need to specify the hours in local time (done), store the locale and convert the specified hours into UTC when conducting any operations.
  has_many :reservations
  has_many :restaurant_managers
  geocoded_by :address, if: :address_changed?

  validates_presence_of :name, :capacity, :phone_number
  validates_presence_of :street_number, :street_name, :city, :province, :postal_code
  validates :capacity, :numericality => {greater_than: 0}
  validates_format_of :phone_number, :with => /\d{3}[ .-]?\d{3}[ .-]?\d{4}/, :message => 'Phone number must be in the
 format XXX-XXX-XXXX. Dashes/spaces/dots optional'

  # TODO Validate that the hours do not overlap.
  # TODO Implement hours as input string.

  # Determines whether capacity is available for a given party size.
  def available?(reservation_time, party_size)
    open_at_time(reservation_time) && available_capacity(reservation_time) >= party_size
  end

  def open_at_time(datetime)
    d = datetime
    start_time = DateTime.new(d.year, d.month, d.day, hours_for_date(datetime)[0])
    end_time = DateTime.new(d.year, d.month, d.day, hours_for_date(datetime)[1])
    datetime.between?(start_time, end_time)
  end

  def available_capacity(reservation_time)
    used_reservations = reservations.where(:date == reservation_time &&(:status == :pending || :status == :accepted)).sum(:party_size)
    capacity - used_reservations
  end

  def hours_for_date(requested_date)
    requested_date # Unused variable would need to be used if hours were set per day.
    JSON.restore(hours)['all_days']
  end

  def set_hours(start_hour, close_hour)
    # POC assumes same hours every day of the week.
    self.hours = JSON.generate({:all_days => [9,20]})
  end

  def address
    [street_number.to_s + ' ' + street_name, city, province, country, postal_code].join(',')
  end

  def address_changed?
    street_number_changed? || street_name_changed? || city_changed? || province_changed? || country_changed? || postal_code_changed?
  end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to admin_root_path
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
      redirect_to admin_root_path
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to admin_root_path
  end

  helper_method 'current_user'

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :capacity, :phone_number, :street_number, :street_name, :city, :province, :country, :postal_code)
  end
end

app/controllers/customer/restaurant_controller.rb
class Customer::RestaurantController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  # def restaurant_params
  #   params.require(:restaurant).permit(:name, :capacity, :phone_number, :street_number, :street_name, :city, :province, :country, :postal_code)
  # end
  
end

app/controllers/customer/restaurants_controller.rb
class Customer::RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  # def restaurant_params
  #   params.require(:restaurant).permit(:name, :capacity, :phone_number, :street_number, :street_name, :city, :province, :country, :postal_code)
  # end
  
end

app/controllers/manager/restaurants_controller.rb
class Manager::RestaurantsController < Manager::ManagersController
  before_action :get_restaurant

  def show
  end


  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    if @restaurant.save
      redirect_to manager_root_path, notice: 'Restaurant Updated'
    else
      render 'manager/restaurant/edit'
    end
  end

  private

  def get_restaurant
    @restaurant = current_user.restaurant
  end

  def restaurant_params
    # TODO Hours needs to be implemented.
    params.require(:restaurant).permit(:name, :phone_number, :street_number, :street_name, :city, :province, :country, :postal_code)
  end


end

app/controllers/restaurant/reservations_controller.rb
class Restaurant::ReservationsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :handle_not_found
  before_action :find_reservation

  def approve
    @reservation.status = :accepted
    if @reservation.save
      redirect_to restaurant_root_path, notice: "Reservation #{@reservation.id} accepted."
    else
      redirect_to restaurant_root_path, notice: "Reservation #{@reservation.id} could not be approved"
    end
  end

  def reject
    @reservation.status = :accepted
    if @reservation.save
      redirect_to restaurant_root_path, notice: "Reservation #{@reservation.id} declined."
    else
      redirect_to restaurant_root_path, notice: "Reservation #{@reservation.id} could not be declined."
    end
  end

  private

  def find_reservation
    @reservation = current_user.restaurant.reservations.find(params[:id])
  end

  def current_user
    # TODO Replace with current user method once available.
    RestaurantManager.first
  end

  def handle_not_found
    redirect_to restaurant_root
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurant/reservations_helper.rb
module Restaurant::ReservationsHelper
end

app/helpers/restaurant/restaurant_helper.rb
module Restaurant::RestaurantHelper
end

app/views/admin/restaurants/_user_input_form.html.erb
<%= form_for @restaurant, url: edit_admin_restaurant_path do |f| %>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :capacity %>
      <%= f.text_field :capacity %>
    </div>
    <div>
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
    <div>
      <%= f.label :street_number%>
      <%= f.text_field :street_number %>
    </div>
    <div>
      <%= f.label :street_name %>
      <%= f.text_field :street_name %>
    </div>
    <div>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div>
      <%= f.label :province %>
      <%= f.text_field :province %>
    </div>
    <div>
      <%= f.label :country %>
      <%= f.text_field :country %>
    </div>
    <div>
      <%= f.label :postal_code %>
      <%= f.text_field :postal_code %>
    </div>
    <div>
      <%= f.submit "Save restaurant" %>
    </div>
<% end %>

app/views/admin/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<p>

</p>

<%= render 'user_input_form', locals: {user: @user} %>

app/views/admin/restaurants/new.html.erb
<h1>Add new restaurant</h1>

<%= form_for @restaurant, url: admin_restaurants_path do |f| %>

    <% if @restaurant.errors.any? %>
        <div>
          <h2>Form Invalid</h2>
          <ul>
            <% @restaurant.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :capacity %>
      <%= f.text_field :capacity %>
    </div>
    <div>
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
    <div>
      <%= f.label :street_number%>
      <%= f.text_field :street_number %>
    </div>
    <div>
      <%= f.label :street_name %>
      <%= f.text_field :street_name %>
    </div>
    <div>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div>
      <%= f.label :province %>
      <%= f.text_field :province %>
    </div>
    <div>
      <%= f.label :country %>
      <%= f.text_field :country %>
    </div>
    <div>
      <%= f.label :postal_code %>
      <%= f.text_field :postal_code %>
    </div>
    <div>
      <%= f.submit "Add restaurant" %>
    </div>
<% end %>