config/routes.rb
Rails.application.routes.draw do

  root 'customer/restaurants#index'

  resources :sessions, only: [:new, :create, :destroy] # Yung

  namespace :customer do #Phil
    root '/customer/customers#show'
  end

  namespace :manager, shallow: true do
    root 'restaurants#show'
    resource(:restaurant, only:[:edit, :show, :update]) do
      resources(:reservations, only: []) do #Rich
        member do
          post 'approve'
          post 'reject'
        end
      end
    end

  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :restaurants, except: [:index]
    resources :managers, except: [:index]
  end

  scope module: 'customer' do
    resources :customers, except: [:index] do
      resources :reservations, only: [:index, :show, :edit, :update] do
        member do 
          patch 'cancel'
        end
      end
    end
    resources :restaurants, only: [:index, :show] do
      resources :reservations, only: [:new, :create]
    end
  end

end

=begin
Sessions - Phil
  Handles log/log out.
Customer - Yung
  List of available restaurants.
  Sign-up for Customers
Reservations - Phil
  Create a reservation.
  View a reservation.
  Cancel a reservation.
Restaurant - Rich
  View reservations.
  Approve reservation.
  Decline reservation.
Admin - Rich
  List of all restaurants
  Approve or decline membership requests.
  Create admins and restaurant users.

=end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :email
  has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
    @administrator = Administrator.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @administrat = Administrator.new(administrator_params)

    if @administrator.save
      redirect_to admin_root_path
    else
      render :new
    end
  end

  def update
    @administrator = Administrator.find(params[:id])

    if @administrator.update_attributes(administrator_params)
      redirect_to admin_root_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_root_path
  end

  helper_method 'current_user'
  private
  def administrator_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone_number)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_user_input_form.html.erb
<%= form_for @user, url: admin_user_path do |f| %>

    <% if @user.errors.any? %>
        <div>
          <h2>Form Invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= %>
    <div>
      <%= f.submit "Edit User" %>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<p>

</p>

<%= render 'user_input_form' %>

app/views/admin/users/new.html.erb
<h1>Sign up a new user</h1>

<%= form_for @user, url: admin_users_path do |f| %>

    <% if @user.errors.any? %>
        <div>
          <h2>Form Invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div>
      <%= f.submit "Add Administrator" %>
    </div>
<% end %>