config/routes.rb
Rails.application.routes.draw do

  root 'customer/restaurants#index'

  resources :sessions, only: [:new, :create, :destroy] # Yung

  namespace :customer do #Phil
    root '/customer/customers#show'
  end

  namespace :manager, shallow: true do
    root 'restaurants#show'
    resource(:restaurant, only:[:edit, :show, :update]) do
      resources(:reservations, only: []) do #Rich
        member do
          post 'approve'
          post 'reject'
        end
      end
    end

  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :restaurants, except: [:index]
    resources :managers, except: [:index]
  end

  scope module: 'customer' do
    resources :customers, except: [:index] do
      resources :reservations, only: [:index, :show, :edit, :update] do
        member do 
          patch 'cancel'
        end
      end
    end
    resources :restaurants, only: [:index, :show] do
      resources :reservations, only: [:new, :create]
    end
  end

end

=begin
Sessions - Phil
  Handles log/log out.
Customer - Yung
  List of available restaurants.
  Sign-up for Customers
Reservations - Phil
  Create a reservation.
  View a reservation.
  Cancel a reservation.
Restaurant - Rich
  View reservations.
  Approve reservation.
  Decline reservation.
Admin - Rich
  List of all restaurants
  Approve or decline membership requests.
  Create admins and restaurant users.

=end

app/views/admin/admin/index.html.erb
<h1>Administrators Page</h1>
<p>Hello Administrator: <%= current_user.name %></p>
<h2>Users</h2>
<td><%= link_to "Sign up new customer", new_customer_path%></td> |
<tb><%= link_to "Create a new restaurant manager user", new_admin_manager_path %></tb>|
<td><%= link_to "Create a new admin user", new_admin_user_path %> </td>

<br/>
<table>
  <thead>
      <tr>
        <th>User Name</th>
        <th>User type</th>
        <th>User Phone Number</th>
        <th>User Email</th>
        <th>Edit User</th>
        <th>Delete User</th>
      </tr>
  </thead>
  <tbody>
  <%= User.find_each do |user|%>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.type %></td>
      <td><%= user.phone_number %></td>
      <td><%= user.email %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user.id) %></td>
      <td><%= link_to "Delete", admin_user_path(user.id), method: :delete, data: {confirm: "Are you sure you want to delete this user?"}  %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br/>
<br/>

<h2>Restaurants</h2>
<td><%= link_to "Add a restaurant", new_admin_restaurant_path %></td>
<table>
      <tr>
        <th>Restaurant Name</th>
        <th>Street Address</th>
        <th>City</th>
        <th>Province</th>
        <th>Country</th>
        <th>Postal Code</th>
        <th>Operating Hours</th>
        <th>Approval</th>
      </tr>
    <tr>
  <tbody>
  <%= Restaurant.find_each do |place| %>
      <td><%= place.name %></td>
      <td><%= place.street_number %> <%= place.street_name %></td>
      <td><%= place.city %></td>
      <td><%= place.province %></td>
      <td><%= place.postal_code %></td>
      <td><%= place.country %></td>
      <td><%= place.hours %></td>
      <td><%= link_to "Delete", admin_restaurant_path(place.id), method: :delete, data: {confirm: "Are you sure
      you want to
      delete this restaurant?"}  %></td>
      </tr>
      <% end %>
  </tbody>

</table>
</p>

app/views/admin/admin/new.html.erb
<h1>Sign up a new administrator</h1>

<%= form_for @administrator do |f| %>

    <% if @adminstrator.errors.any? %>
        <div>
          <h2>Form Invalid</h2>
          <ul>
            <% @administrator.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div>
      <%= f.submit "Add Administrator" %>
    </div>
<% end %>